version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  integration-tests:
    jobs:
      - api-tests
jobs:  
  api-tests:
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build --logger "trx"
      - run:
          name: test results
          when: always
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
         #path: NetRelayTechnical
  